# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e02225ed1ce4ae3efc8669b3339cfe50f75e72260a24fa66d2a3ad54523eaa7b774bf7c320582b9de210cf4ef7e507f15a79c9bacb1c10a9fe1af7c8b1bc612

test:
  secret_key_base: d992782b840666893c71f2bec3417a3d03dd206be25d809fd5ec804965f4e6bfa02825cabc578213159147922f448eaf4a44490f24bb9a010888dd19735ed3d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
